# Test configuration file - do not use for production
configurations:
  test:
    name: "Test Environment"
    config:
      MYSQL_EXPORT_HOST: "test-host"
      MYSQL_EXPORT_PORT: "3306"
      MYSQL_EXPORT_DATABASE: "test_db"
      MYSQL_EXPORT_USER: "test_user"
      MYSQL_EXPORT_PASSWORD: "test_pass"
      MYSQL_EXPORT_BACKUP_DIR: "/backup"
      MYSQL_IMPORT_HOST: "localhost"
      MYSQL_IMPORT_PORT: "3306"
      MYSQL_IMPORT_DATABASE: "test_db"
      MYSQL_IMPORT_USER: "test_user"
      MYSQL_IMPORT_PASSWORD: "test_pass"
      SSH_HOST: "test-host"
      SSH_USER: "test_user"
      SSH_PASSWORD: "test_pass"
