version: '3.8'

services:
  test-run:
    build:
      context: .
      dockerfile: Dockerfile.test-run
    volumes:
      - ./dist:/app/dist
      - ./mysql_sync_manager/db_configs.yml:/app/db_configs.yml
      - ../../../.ssh:/var/www/html/.ssh:rw
    tty: true
    stdin_open: true
    user: root
    networks:
      - shop_network
      - snosm-cakephp2_default

networks:
  shop_network:
    external: true
  snosm-cakephp2_default:
    external: true