version: '3.8'

services:
  build:
    image: mysqlsyncmanager-build
    build:
      context: .
      dockerfile: Dockerfile.build
    volumes:
      - ./dist:/app/dist
    environment:
      - PYTHONPATH=/app