name: Docker Tests

on:
  workflow_dispatch:  # Manual trigger only
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run tests
        run: |
          docker compose -f docker-compose.test.yml build
          docker compose -f docker-compose.test.yml up --exit-code-from test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: docker-tests
          fail_ci_if_error: true