version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    mem_limit: 512m
    memswap_limit: 512m
    command: >
      sh -c "
      python -m pytest -v \
      tests/test_main.py \
      tests/test_backup.py \
      tests/test_config.py \
      tests/test_core.py \
      tests/test_db.py \
      tests/test_ssh.py \
      --cov=backup_operations \
      --cov=config \
      --cov=menu \
      --cov=db \
      --cov=ssh \
      --cov=retry_utils \
      --cov=exceptions \
      --cov=utils \
      --cov=main \
      --cov-report=term-missing \
      --cov-report=xml:coverage.xml \
      --timeout=60"