name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build executable
        run: |
          docker compose -f docker-compose.build.yml build
          docker compose -f docker-compose.build.yml up

      - name: Debug - List dist directory contents
        run: |
          ls -la dist/
          pwd

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ github.ref_name }}
          files: |
            dist/mysql-sync-manager
            dist/db_configs.yml
          generate_release_notes: true
          draft: false
          prerelease: false

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mysql-sync-manager-${{ github.ref_name }}
          path: |
            dist/mysql-sync-manager
            dist/db_configs.yml
          retention-days: 5