name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # This is crucial for creating releases and uploading assets

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build executable
        run: |
          docker compose -f docker-compose.build.yml build
          docker compose -f docker-compose.build.yml up

      - name: Debug - List project contents
        run: |
          echo "Current directory contents:"
          ls -la
          echo "\nDocker images:"
          docker images
          echo "\nTrying to extract files from built image:"
          IMAGE_NAME=$(docker images -q mysqlsyncmanager-build)
          if [ -n "$IMAGE_NAME" ]; then
            CONTAINER_NAME=$(docker create $IMAGE_NAME)
            docker cp $CONTAINER_NAME:/app/dist ./extracted_dist
            docker rm $CONTAINER_NAME
          fi
          ls -la extracted_dist || true
          echo "\nSystem disk space:"
          df -h

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            extracted_dist/mysql-sync-manager
            extracted_dist/db_configs.yml
          generate_release_notes: true
          draft: false
          prerelease: false

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mysql-sync-manager-${{ github.ref_name }}
          path: ./extracted_dist/*
          retention-days: 5