name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step to check out the repository
      - uses: actions/checkout@v3

      # Step to use Docker Compose directly
      - name: Run Docker Compose Tests
        uses: docker/compose-action@v2
        with:
          compose-file: docker-compose.test.yml
          run: up --exit-code-from test

      # Step to upload test coverage reports
      - name: Upload Coverage Reports
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
          fail_ci_if_error: true
