# .github/workflows/github-test.yml
name: GitHub Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov pytest-timeout pytest-mock

      - name: Create test config directory
        run: |
          mkdir -p /var/www/html
          touch /var/www/html/db_configs.yml

      - name: Run tests
        run: |
          python -m pytest -v \
            tests/test_main.py \
            tests/test_backup.py \
            tests/test_config.py \
            tests/test_core.py \
            tests/test_db.py \
            tests/test_ssh.py \
            --cov=backup_operations \
            --cov=config \
            --cov=menu \
            --cov=db \
            --cov=ssh \
            --cov=retry_utils \
            --cov=exceptions \
            --cov=utils \
            --cov=main \
            --cov-report=term-missing \
            --cov-report=xml:coverage.xml \
            --log-cli-level=DEBUG \
            -s

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: github-tests
          fail_ci_if_error: true