name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Set up Docker Buildx (includes Docker CLI with Compose v2 support)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and run the Docker Compose tests
      - name: Run Docker Compose Tests
        run: |
          docker compose -f docker-compose.test.yml build
          docker compose -f docker-compose.test.yml up --exit-code-from test

      # Generate coverage report
      - name: Generate coverage report
        run: |
          # Assuming you're using pytest to run tests
          docker-compose exec -T test pytest -v tests/ --timeout=30 --cov=./ --cov-report=term-missing --cov-report=xml:coverage.xml

      # Upload Coverage Reports to Codecov
      - name: Upload Coverage Reports
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }} 
          file: ./coverage.xml
          flags: unittests
          fail_ci_if_error: true